//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfLatencyTestClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ILatencyTestService")]
    public interface ILatencyTestService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILatencyTestService/Sync", ReplyAction="http://tempuri.org/ILatencyTestService/SyncResponse")]
        void Sync(System.TimeSpan clientTimestamp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILatencyTestService/Sync", ReplyAction="http://tempuri.org/ILatencyTestService/SyncResponse")]
        System.Threading.Tasks.Task SyncAsync(System.TimeSpan clientTimestamp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILatencyTestService/Operation", ReplyAction="http://tempuri.org/ILatencyTestService/OperationResponse")]
        System.TimeSpan Operation(System.TimeSpan delay, System.TimeSpan clientTimestamp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILatencyTestService/Operation", ReplyAction="http://tempuri.org/ILatencyTestService/OperationResponse")]
        System.Threading.Tasks.Task<System.TimeSpan> OperationAsync(System.TimeSpan delay, System.TimeSpan clientTimestamp);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILatencyTestServiceChannel : WcfLatencyTestClient.ServiceReference1.ILatencyTestService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LatencyTestServiceClient : System.ServiceModel.ClientBase<WcfLatencyTestClient.ServiceReference1.ILatencyTestService>, WcfLatencyTestClient.ServiceReference1.ILatencyTestService {
        
        public LatencyTestServiceClient() {
        }
        
        public LatencyTestServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LatencyTestServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LatencyTestServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LatencyTestServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Sync(System.TimeSpan clientTimestamp) {
            base.Channel.Sync(clientTimestamp);
        }
        
        public System.Threading.Tasks.Task SyncAsync(System.TimeSpan clientTimestamp) {
            return base.Channel.SyncAsync(clientTimestamp);
        }
        
        public System.TimeSpan Operation(System.TimeSpan delay, System.TimeSpan clientTimestamp) {
            return base.Channel.Operation(delay, clientTimestamp);
        }
        
        public System.Threading.Tasks.Task<System.TimeSpan> OperationAsync(System.TimeSpan delay, System.TimeSpan clientTimestamp) {
            return base.Channel.OperationAsync(delay, clientTimestamp);
        }
    }
}
